{
  "hash": "4badc7cf57cf50712258c484c28abf05",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Teste de Normalidade e Homogeneidade\"\nformat: html\n---\n\n\n\nAntes de realizar análises estatísticas, é importante verificar se os dados atendem a certas premissas para garantir resultados confiáveis. Entre essas premissas estão a normalidade e a homogeneidade de variâncias. O teste de normalidade verifica se os dados seguem uma distribuição normal, sendo esta uma suposição necessária em muitos testes paramétricos, como o teste t. Para avaliar a normalidade, podem ser utilizados testes como Shapiro-Wilk e Anderson-Darling além da inspecção visual por histogramas e gráficos Q-Q plot. Outro aspecto importante é verificar a homogeneidade de variâncias, que consiste em avaliar se os grupos possuem variâncias semelhantes. Essa condição é essencial para o uso correto do teste t padrão. Se as variâncias forem diferentes entre os grupos, pode-se utilizar o teste t de Welch, que é apropriado para situações com variâncias heterogêneas. Para verificar a homogeneidade de variâncias, é comum utilizar o teste de Levene, que é robusto mesmo quando os dados não seguem uma distribuição normal, e o teste de Bartlett, que é indicado quando os dados são normalmente distribuídos. Visualizações como boxplots também ajudam a identificar diferenças nas variâncias entre os grupos.\n\nRealizar os testes de normalidade e homogeneidade de variâncias antes de prosseguir com análises estatísticas garante a confiabilidade das conclusões e evita interpretações equivocadas dos dados analisados.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(car) # Funções de análise estatística avançadas (ANOVA, testes de homogeneidade).\n```\n:::\n\n\n\n### Shapiro-Wilk\n\nTesta normalidade dos dados.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshapiro.test(dat_mg2$Mg2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  dat_mg2$Mg2\nW = 0.97269, p-value = 0.9146\n```\n\n\n:::\n:::\n\n\n\n-   p-value = 0.9146 → muito maior que 0.05\n\n-   Não rejeitamos H₀, ou seja, os dados de `Mg2` podem ser considerados normalmente distribuídos.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshapiro.test(dat_mg2$control)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  dat_mg2$control\nW = 0.93886, p-value = 0.5404\n```\n\n\n:::\n:::\n\n\n\n-   p-value = 0.5404 → também maior que 0.05\n\n-   Os dados de `control` também seguem uma distribuição normal.\n\n### Histogramas\n\nVisualização da distribuição.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhist(dat_mg2$Mg2, main = \"Histograma de Mg2\", xlab = \"Valores de comp\")\n```\n\n::: {.cell-output-display}\n![](nh_test_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n\n```{.r .cell-code}\nhist(dat_mg2$control, main = \"Histograma de Controle\", xlab = \"Valores de comp\")\n```\n\n::: {.cell-output-display}\n![](nh_test_files/figure-html/unnamed-chunk-5-2.png){width=672}\n:::\n:::\n\n\n\n### Gráficos Q-Q plot\n\nGráfico Q-Q (quantil-quantil) dos resíduos, que ajuda a visualizar se eles seguem uma distribuição normal.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqqnorm(residuals(m2))\nqqline(residuals(m2))\n```\n\n::: {.cell-output-display}\n![](nh_test_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\n\n### Teste F\n\nTestar a homogeneidade de variânciascoms de **dois grupos** apenas.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvar.test(dat_mg2$Mg2, dat_mg2$control)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tF test to compare two variances\n\ndata:  dat_mg2$Mg2 and dat_mg2$control\nF = 1.4781, num df = 9, denom df = 9, p-value = 0.5698\nalternative hypothesis: true ratio of variances is not equal to 1\n95 percent confidence interval:\n 0.3671417 5.9508644\nsample estimates:\nratio of variances \n          1.478111 \n```\n\n\n:::\n:::\n\n\n\n-    Esses testes verificam **as premissas do teste t**.\n\n### Teste de Barttlet\n\nTambém testa a homogeneidade de variâncias de **dois ou mais grupos**.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbartlett.test(count ~ spray, data = insetos)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tBartlett test of homogeneity of variances\n\ndata:  count by spray\nBartlett's K-squared = 25.96, df = 5, p-value = 9.085e-05\n```\n\n\n:::\n:::\n\n\n\n-   Bartlett’s K-squared = 25.96: é o valor estatístico do teste.\n\n-   df = 5: são os graus de liberdade (número de grupos − 1, no caso, 6 sprays).\n\n-   p-value = 9.085e-05 (ou 0.00009085): é muito menor que 0.05.\n\n**p-valor é muito pequeno**, **rejeitamos a hipótese nula (H₀)**. **Isso significa que as variâncias entre os grupos são significativamente diferentes.**\n",
    "supporting": [
      "nh_test_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}