project:
  type: website
  output-dir: docs

website:
  title: "CADERNO DE AULAS"
  navbar:
    background: "#87CEEB"
    primary: "#B0E0E6"
    left:
      - text: "Início"
        href: index.qmd

      - text: "Introdução ao R"
        menu:
          - text: "Definição e Instalação"
            href: Introdução_ao_R.qmd
          - text: "Importação de dados"
            href: Importando_dados.qmd
      
      - text: "Manipulação de Dados"
        menu:
          - text: "Pacotes"
            href: pacotedplyr.qmd
          - text: "Gráficos"
            href: graficos.qmd
            
      - text: "Análises Estatísticas"
        menu:
          - text: "Teste t"
            href: test_t.qmd
          - text: "Teste de Normalidade e Homogeneidade"
            href: nh_test.qmd
          - text: "ANOVA"
            href: ANOVA.qmd
          - text: "Teste de Krustal-Wallis"
            href: KW_test.qmd
          - text: "Regressão Linear e Análise de Resíduos"
            href: lm.qmd
          - text: "Tranformação Box-Cox"
            href: boxcox.qmd

      - text: "Construção de Mapas"
        href: mapa.qmd

    right:
      - icon: github
        href: "https://github.com/seu-usuario"
      - icon: search

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    include-after-body:
      - text: |
          <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.0/font/bootstrap-icons.css">
    include-in-header:
      - text: |
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
          <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;600&family=Playfair+Display:wght@700&display=swap" rel="stylesheet">
